Fix NoSuchMethodError when sending PacketServerChat packet. This issue is caused by old BungeeCord (before https://github.com/SpigotMC/BungeeCord/commit/0f5f09b6c5f073130515c8cd435541c5c68bcba8)